- hosts: all
  become: yes
  tasks:
    - name: Clean up resources for csi manila acceptance tests
      shell:
        cmd: |
          set -e
          set -x

          '{{ kubectl }}' config use-context local

          for f in \
            examples/manila-csi-plugin/nfs/snapshot/pod.yaml \
            examples/manila-csi-plugin/nfs/snapshot/snapshotrestore.yaml \
            examples/manila-csi-plugin/nfs/snapshot/snapshotcreate.yaml \
            examples/manila-csi-plugin/nfs/dynamic-provisioning/pod.yaml \
            examples/manila-csi-plugin/nfs/dynamic-provisioning/pvc.yaml
          do
            timeout 300 '{{ kubectl }}' delete -f "$f"
          done

        executable: /bin/bash
        chdir: '{{ k8s_os_provider_src_dir }}'
      environment: '{{ global_env }}'
